version: '3'
services:
  wbip:
    build: .
    ports:
      - 8081:8081
    volumes:
      - ./data:/data
    depends_on:
      - postlight
  postlight:
    build: ./postlight/
    restart: unless-stopped
    ports:
     - 3000:3000
